# Generated by Django 5.2.7 on 2025-11-20 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cars_brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BRAND_NAME', models.CharField(max_length=100)),
                ('BRAND_COUNTRY', models.CharField(max_length=100)),
                ('BRAND_RATING', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='cars_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CAR_NAME', models.CharField(max_length=100)),
                ('CAR_MODEL', models.CharField(max_length=50)),
                ('CAR_PRICE', models.FloatField()),
                ('CAR_BRAND', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duikt_task_zhylyk.cars_brand')),
            ],
        ),
    ]
